= GUI Architecture overview
== Application components
Key GUI application components:
  - events
  - message bus
  - ui system
    - windows
    - widgets
    - controllers: embedded, user
    - versioned view models
    - bindings

An *event* is a named set of data that conveys information about a performed
user input, timer, task completion, error notification that may need to be taken
action on.

The *message bus* is a FIFO queue of events. Events are generated by the UI
system, cotrollers. The bus is used to send events with parameters from UI and
between app logic parts to decouple ui, logic, models code.

The *UI system* object manages windows, OS events, widgets, controllers.

A *widget* is a basic building block of the UI tree. It may be invisible, have
colour or texture background, transparent, may just serve to maintain layout,
may contain other widgets and thus build a tree. Widgets that produce events are
also called controls.

*Controllers* are either user code or embedded -- implemented by the ui
 system. They update models, receive events, initiate app shutdown, implement
 domain logic.

A *window* is an object that is tied to the OS displayed application
window/surface, has a root widget which is also the embedded controller for that
window.

*Models* are versioned sets of data. When any part of the data is changed the
version is incremented. There may be multiple instances of the models under same
or different names in the UI system.

*Bindings* are refrences to the model instance. A binding is an expression that
resolves to the data field. Models' version change triggers widgets' updates.

An *embedded controller* is a role of a widget in the hierarchy. It introduces
the boundary of model bindings down the hierarchy, filters and translates events
from the children. It can also introduce new model instances that are evaluated
from parameters.

Only declared embedded controller's parameters are visible to the controls
down the tree up to the next embedded controller down the tree.

Only events declared in the embedded controller are propagated up the tree.

*User controllers* are managed as a stack. The last added controller receives
events first. A controller can consume an event and prevent other controllers
up the stack receiving the event, which makes possible to proragate system
events to the root (like window close/quit) while still implement modal
dialogs.

UI system is built on windows. All input, OS windowing events are first
handled by the UI system and then sent to app logic by the following path: ui
system -> control -> embedded controllers -> user controllers.

UI controls generate custom events. Only events declared in the embedded
controller are propagated to the parent embedded controller. Only events that
are declared by the root embedded controller (root window widget) rich the user
controllers.
