= GUI Architecture overview
== Application components
Key GUI application components:
  - events
  - message bus
  - ui system
    - layout system
    - windows
    - widgets
    - controllers: embedded, user
    - versioned view models
    - bindings

An *event* is a named set of data that conveys information about a performed
user input, timer, task completion, error notification that may need to be taken
action on.

The *message bus* is a thread-safe FIFO queue of events. Events are generated by
the UI system, controllers. The bus is used to send events with parameters from
UI and between app logic parts to decouple ui, logic, models code. Sending
events to the bus wakes the platform-specific (SDL) event loop via a custom
event if necessary (e.g. for background threads to signal progress).

The *UI system* object manages windows, OS events, widgets, controllers.

The *layout system* recalculates widgets sizes and positions.

A *widget* is a basic building block of the UI tree. It may be invisible,
disabled, have a colour or texture background, be transparent, may just serve to
maintain layout, may contain other widgets and thus build a tree. Widgets that
produce or consume events are also called controls. Invisible and disabled
widgets do not participate in events handling.

*Controllers* are either user code or embedded -- implemented by the ui
system. They update models, receive events, initiate app shutdown, implement
domain logic.

A *window* is an object that is tied to the OS displayed application
window/surface, has a root widget which is also the embedded controller for that
window.

*Models* are versioned sets of data. When any part of the data is changed the
version is incremented. There may be multiple instances of the models under same
or different names in the UI system. Version relates to the whole model
structure, i.e. not per field. References to other models via fields do not
increment version of the model that has a reference to the changed one.  If a
model has many fields where most fields are not updated most of the time
consider to split it into smaller structures grouped by update frequency to
minimize updates.

*Bindings* are references to the model instance. A binding is an expression that
resolves to the data field. Models' version change triggers widgets' updates.

An *embedded controller* is a role of a widget in the hierarchy. It introduces
the boundary of model bindings down the hierarchy, filters and translates events
from the children. It can also introduce new model instances that are evaluated
from parameters.

Only declared embedded controller's parameters are visible to the controls
down the tree up to the next embedded controller down the tree.

Only events declared in the embedded controller are propagated up the tree.

*User controllers* are managed as a stack. The last added controller receives
events first. A controller can consume an event and prevent other controllers
up the stack receiving the event, which makes possible to propagate system
events to the root (like window close/quit) while still implement modal
dialogs.

UI system is built on windows. All input, OS windowing events are first handled
by the UI system and then sent to app logic by the following path: ui system ->
message bus -> controls -> embedded controllers -> message bus ->
user controllers.

UI controls generate custom events. Only events declared in the embedded
controller are propagated to the parent embedded controller. Only events that
are declared by the root embedded controller (root window widget) reach the user
controllers.

== Event types
The following events are on the bus based on the sender:
    - system
    - embedded controller
    - user

== Event flow
An SDL event is received by the UI system. The UI system either ignores an
unsupported event or translates it into a message and puts into to the bus.

The UI system reads events from the bus. For each control from the leaf to the
root call handleEvent method, if the control consumes the event then stop tree
traversal.

A control may produce a new event based on the received input event, but does
not put it on to the bus, it returns the event from handleEvent method and the
UI system translates it via embedded controllers up the tree (stop on the first
controller to consume).

If the root embedded controller translates/exports the event it is put on the
bus for user controllers to consume. Events translation means exporting it under
a different name, e.g. when reusing a subtree for an input field with a label
the input control will send event "text_changed" but the embedded controller will
export it as "email_text_changed" up the tree.

After all controls are processed the UI system calls handleEvent for the user
controllers' stack.

User controllers notify the UI system if there are model changes.

== Bindings update
If user controllers notify about changes to the models, the UI system calls
update() on embedded controllers.

Embedded controllers check version of their model instances and reevaluate
bindings expressions and call update() on widgets.

Models are read-only by the widgets. They are updated by user controllers only.
Controls that pass the new data send it via the events, e.g. when a text field
has a changed text, it sends it via the embedded controller to the message bus.

== Bindings evaluation
"modelInstance.field.otherModelReference.arrayField[index]"
TODO design ast? that is constructed for evaluation

== Layout system
The layout system sets the widgets' dirty bit when necessary to trigger redraw.

TODO

== Rendering
Widgets set the dirty bit when necessary to trigger redraw.

TODO

== Input handling
TODO

== Controllers

TODO onSuspend / Resume: when a modal controller is pushed to the stack?
